import { useState } from 'react';
import { LightBulb, Play } from 'iconoir-react';
import Button from '../components/atoms/Button/Button.jsx';
import Chip from '../components/atoms/Chip/Chip.jsx';
import IndicatorDot from '../components/atoms/IndicatorDot/IndicatorDot.jsx';
import SliderHandle from '../components/atoms/SliderHandle/SliderHandle.jsx';
import SliderThumb from '../components/atoms/SliderThumb/SliderThumb.jsx';
import SliderTrack from '../components/atoms/SliderTrack/SliderTrack.jsx';
import Action from '../components/molecules/Binary/Action/Action.jsx';
import CircularGauge from '../components/molecules/Circular/Gauge/CircularGauge.jsx';
import TemperatureControl from '../components/molecules/Circular/TemperatureControl/TemperatureControl.jsx';
import DeviceInfo from '../components/molecules/Display/DeviceInfo/DeviceInfo.jsx';
import Readout from '../components/molecules/Display/Readout/Readout.jsx';
import AdaptiveLightSlider from '../components/molecules/Linear/AdaptiveLightSlider/AdaptiveLightSliderNew.jsx';
import ColorTemperatureSlider from '../components/molecules/Linear/ColorTemperatureSlider/ColorTemperatureSlider.jsx';
import HorizontalSlider from '../components/molecules/Linear/HorizontalSlider/HorizontalSlider.jsx';
import Slider from '../components/molecules/Linear/Slider/Slider.jsx';
import VerticalSlider from '../components/molecules/Linear/VerticalSlider/VerticalSlider.jsx';
import Dropdown from '../components/molecules/Selection/Dropdown/Dropdown.jsx';
import ToggleBtn from '../components/molecules/ToggleBtn/ToggleBtn.jsx';
import BlindCurtain from '../components/organisms/BlindCurtain/BlindCurtain.jsx';
import ActionDeviceCard from '../components/organisms/Cards/ActionDeviceCard/ActionDeviceCard.jsx';
import BinaryDeviceCard from '../components/organisms/Cards/BinaryDeviceCard/BinaryDeviceCard.jsx';
import TabBar from '../components/organisms/Navigation/TabBar/TabBar.jsx';
import SpeakerVolumeControl from '../components/organisms/SpeakerVolumeControl/SpeakerVolumeControl.jsx';
export default function Demo({ name }) {
 const [on,setOn]=useState(false); const [value,setValue]=useState(50); const [temp,setTemp]=useState(4000); const [room,setRoom]=useState('living'); const [count,setCount]=useState(0);
 const [buttonOn,setButtonOn]=useState(true);
 const [stepLevel,setStepLevel]=useState(3);
 const [adaptiveValue,setAdaptiveValue]=useState(0);
 const toggle=()=>setOn(v=>!v);
 let content;
 switch(name) {
 case 'Button': content=<><div className="demo-state"><Button active={buttonOn} onClick={()=>setButtonOn(v=>!v)} aria-label="조명 전환" icon={<LightBulb/>}/><span className="demo-state-label">{buttonOn?'On':'Off'}</span></div><div className="demo-state"><Button active={on} onClick={toggle} aria-label="조명 전환" icon={<LightBulb/>}/><span className="demo-state-label">{on?'On':'Off'}</span></div><div className="demo-state"><Button disabled aria-label="비활성 조명" icon={<LightBulb/>}/><span className="demo-state-label">Disabled</span></div></>;break;
 case 'Chip': content=<>{['전체','조명','센서'].map((label,i)=><Chip key={label} label={label} active={count===i} onClick={()=>setCount(i)}/>)}</>;break;
 case 'SliderTrack': content=<SliderTrack/>;break;
 case 'SliderThumb': content=<SliderThumb style={{position:'relative',left:'auto',top:'auto',transform:'none'}}/>;break;
 case 'SliderHandle': content=<SliderHandle/>;break;
 case 'IndicatorDot': content=<>{['target','current'].map(variant=><div className="dot-sample" key={variant}><IndicatorDot variant={variant} style={{position:'relative',transform:'none'}}/><span>{variant}</span></div>)}</>;break;
 case 'ToggleBtn': content=<div className="demo-state"><ToggleBtn isOn={on} onToggle={toggle}/><span className="demo-state-label">{on?'On':'Off'}</span></div>;break;
 case 'Slider': content=<div className="demo-wide demo-slider-examples"><div><Slider value={value} onChange={setValue} min={0} max={100}/><output className="demo-state-label">Continuous (Brightness: {Math.round(value)}%)</output></div><div><Slider value={stepLevel} onChange={setStepLevel} min={0} max={5} step={1}/><output className="demo-state-label">Step Slider (Level: {stepLevel})</output></div></div>;break;
 case 'VerticalSliderNoIcons': content=<VerticalSlider showIcons={false}/>;break;
 case 'HorizontalSlider': content=<HorizontalSlider value={value} onChange={setValue} showIcons={false} width="300px"/>;break;
 case 'AdaptiveLightSlider': content=<div className="demo-state demo-adaptive-state"><AdaptiveLightSlider value={adaptiveValue} onChange={setAdaptiveValue}/><output className="demo-state-label">{adaptiveValue}%</output></div>;break;
 case 'VerticalSlider': content=<VerticalSlider/>;break;
 case 'ColorTemperatureSlider': content=<div className="demo-wide"><ColorTemperatureSlider value={temp} onChange={setTemp}/><output className="demo-state-label">{temp} K</output></div>;break;
 case 'CircularGauge': content=<div style={{width:240,height:240}}><CircularGauge size={240} radius={100} center={120} strokeWidth={16} startAngle={135} totalAngle={270} circumference={2*Math.PI*100} segmentLength={350} offsetLength={0} gradientId="docs-gauge" gradientColors={[{offset:'0%',color:'var(--sys-color-temp-warm)'},{offset:'100%',color:'var(--sys-color-temp-cool)'}]}/></div>;break;
 case 'TemperatureControl': content=<TemperatureControl targetTemp={18+value/100*12} currentTemp={22} onChange={v=>setValue((v-18)/12*100)} gradientId="docs-temperature"/>;break;
 case 'Readout': content=<Readout value={24} unit="°C" label="현재 온도"/>;break;
 case 'DeviceInfo': content=<DeviceInfo name="거실 조명" location="거실" status="켜짐" isOn/>;break;
 case 'Dropdown': content=<Dropdown value={room} options={[{value:'living',label:'거실'},{value:'bedroom',label:'침실'}]} onChange={v=>setRoom(v.value)}/>;break;
 case 'Action': content=<><Action onClick={()=>setCount(v=>v+1)} aria-label="실행" icon={<Play/>}/><output>{count}회 실행</output></>;break;
 case 'BinaryDeviceCard': content=<BinaryDeviceCard style={{width:300,maxWidth:'100%'}} name="Living room light" status={on?'On':'Off'} isOn={on} onToggle={toggle} icon={<LightBulb/>}/>;break;
 case 'ActionDeviceCard': content=<ActionDeviceCard name="스피커" status={on?'재생 중':'일시 정지'} isPlaying={on} onAction={toggle} icon={<Play/>}/>;break;
 case 'SpeakerVolumeControl': content=<SpeakerVolumeControl initialVolume={45}/>;break;
 case 'BlindCurtain': content=<BlindCurtain/>;break;
 case 'TabBar': content=<TabBar/>;break;
 default: content=null;
 }
 return <div className="live-demo">{content}</div>;
}
