import { useEffect, useRef, useState } from 'react';
import { ThinkingOrb } from 'thinking-orbs';
import catalog from './docs/catalog.json';
import deviceUsage from './docs/device-usage.json';
import Demo from './docs/Demo';
import ComponentThumbnail from './docs/ComponentThumbnail';
import SidebarGroup from './docs/SidebarGroup';
import SourceCode from './docs/SourceCode';
import { classify, behaviorLabel } from './docs/classification';
import DesignToken from './docs/DesignToken';
import Validation from './docs/Validation';
import Landing from './docs/Landing';
import Experience from './docs/Experience';
import AIChat from './docs/AIChat';
import AIQuickChat from './docs/AIQuickChat';
import Dashboard from './components/pages/Dashboard/Dashboard';
import Lighting from './components/pages/LightingControl/LightingControl';
import AirConditioner from './components/pages/AirConditionerControl/AirConditionerControl';
import Curtain from './components/pages/SmartCurtainControl/SmartCurtainControl';
import Speaker from './components/pages/SpeakerControl/SpeakerControl';
import Washer from './components/pages/WasherControl/WasherControl';
import Refrigerator from './components/pages/RefrigeratorControl/RefrigeratorControl';
import './App.css';
const sources = import.meta.glob('./components/**/*.jsx', { query: '?raw', import: 'default', eager: true });
const devices=[['dashboard','Dashboard','집 안의 기기를 한눈에 확인하는 대시보드',Dashboard],['lighting','Lighting','전원·밝기·색온도를 조절하는 조명 화면',Lighting],['airconditioner','Air Conditioner','현재 온도와 목표 온도를 확인하는 냉방 화면',AirConditioner],['curtain','Smart Curtain','커튼의 개폐 상태와 위치를 조절하는 화면',Curtain],['speaker','Speaker','재생과 볼륨을 조절하는 스피커 화면',Speaker],['washer','Washer','세탁 모드와 실행 상태를 확인하는 화면',Washer],['refrigerator','Refrigerator','냉장·냉동 온도를 조절하는 화면',Refrigerator]];
const notes={VerticalSliderNoIcons:'VerticalSlider에 showIcons={false}를 전달합니다. 내부 상태로 동작하며 value·onChange·disabled 속성은 아직 지원하지 않습니다.',AdaptiveLightSlider:'Adaptive Light Slider와 아이콘 있는 Vertical Slider를 함께 비교합니다. Adaptive Light Slider는 onChange로 변경값을 전달하며 height 속성은 지원하지 않습니다. Vertical Slider는 내부 상태로 동작합니다.',TabBar:'현재 구현은 정적인 탐색 예시입니다. 탭 선택이나 페이지 이동 기능은 포함하지 않습니다.',BlindCurtain:'현재 내부 슬라이더로 동작하는 예시이며 외부 기기 상태와 연결되어 있지 않습니다.'};
const basics=[['start','시작하기','Flowthing을 사용하는 방법'],['foundations','Foundations','색상 · 타이포그래피 · 그림자 · 디자인 토큰'],['components','Components','스마트홈을 구성하는 모든 UI'],['devices','Devices','기기별 화면과 구성 예시'],['development','Development','Developer Guide · Patterns · AI Guardrails · Design Guidelines'],['updates','업데이트','문서 구조 변경 기록']];
const readRoute=()=>{const path=location.hash.slice(1).split('?')[0]||'/start';return ({'/':'/start','/patterns':'/development/patterns','/rules':'/development/ai-guardrails'})[path]||path.replace(/^\/validation(?=\/|$)/,'/development');};
const validationPages=[['guide','Developer Guide','설치 · 컴포넌트 사용 · 개발 시작'],['patterns','Patterns','기기 연결 · 명령 처리 · 오류 복구'],['ai-guardrails','AI Guardrails','AI 조합 규칙 · 기기 제약'],['design-guidelines','Design Guidelines','타이포그래피 · 배경 · 레이아웃 · 접근성']];
const displayName=name=>name.replace(/([a-z])([A-Z])/g,'$1 $2').replace('Iot ','IoT ');
function Copy({text,label='복사'}) { const [status,setStatus]=useState(''); return <button className="doc-button" onClick={async()=>{try{await navigator.clipboard.writeText(text);setStatus('복사됨');}catch{setStatus('복사할 수 없습니다');}}}>{status||label}</button>; }
export default function App(){
 const [assistantOpen,setAssistantOpen]=useState(false);
 const [assistantHandoff,setAssistantHandoff]=useState(null);
 const expandAssistant=handoff=>{setAssistantHandoff(handoff);setAssistantOpen(false);window.location.assign('#/ai');};
 const closeAssistant=()=>{setAssistantOpen(false);requestAnimationFrame(()=>document.getElementById('ai-floating-entry')?.focus());};
 const [classification,setClassification]=useState('behavior');
 const [showClassification,setShowClassification]=useState(true);
 const [category,setCategory]=useState('binary');
 const [route,setRoute]=useState(readRoute); const [query,setQuery]=useState(''); const [menu,setMenu]=useState(false); const main=useRef(null);
 useEffect(()=>{
 const change=()=>{setRoute(readRoute());setMenu(false);setQuery('');};
 window.addEventListener('hashchange',change);
 return()=>window.removeEventListener('hashchange',change);
 },[]);
 useEffect(()=>{const shortcut=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('header-search-input')?.focus();}if(e.key==='Escape'){setQuery('');setMenu(false);}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[]);
 const parts=route.split('/').filter(Boolean); const kind=parts[0];
 const entry=kind==='components'?catalog.find(c=>c.id===parts[1]):null;
 const device=kind==='devices'?devices.find(d=>d[0]===parts[1]):null;
 const tokenPage=route==='/foundations/design-token'||route==='/foundations/design-token/reference';
 const validationPage=kind==='development'?validationPages.find(v=>route==='/development/'+v[0]):null;
 const valid=entry||device||tokenPage||validationPage||basics.some(b=>'/'+b[0]===route);
 const title=kind==='ai'?'AI Workspace':kind==='experience'?'스마트홈 체험':entry?.title||device?.[1]||validationPage?.[1]||(tokenPage?'Design Token':null)||basics.find(b=>b[0]===kind)?.[1]||'페이지를 찾을 수 없어요';
 useEffect(()=>{document.title=`${title} · Flowthing`;window.scrollTo(0,0);main.current?.scrollTo(0,0);main.current?.focus({preventScroll:true});},[route,title]);
 const searchItems=[...validationPages.map(v=>({path:'/development/'+v[0],title:v[1],description:v[2]})),{path:'/foundations/design-token',title:'Design Token',description:'디자인 토큰의 개념 · 구성 · 사용법'},{path:'/foundations/design-token/reference',title:'Token Reference',description:'디자인 토큰 · 색상 · 글꼴 · 그림자 · 레퍼런스'},...basics.map(b=>({path:'/'+b[0],title:b[1],description:b[2]})),...catalog.map(c=>({path:'/components/'+c.id,...c})),...devices.map(d=>({path:'/devices/'+d[0],title:d[1],description:d[2]}))];
 const results=query.trim()?searchItems.filter(item=>(item.title+' '+item.description).toLowerCase().includes(query.trim().toLowerCase())):[];
 const link=(path,label)=><a key={path} href={'#'+path} className={route===path?'active':''} aria-current={route===path?'page':undefined} onClick={()=>{setMenu(false);if(path==='/components')setShowClassification(true);}}>{label}</a>;
 const scrollTo=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});
 const examples=entry?devices.filter(d=>(deviceUsage[entry.id]||[]).includes(d[0])):[];
 const source=entry?sources['./'+entry.source.slice(4)]:'';
 const sections=tokenPage?(route.endsWith('/reference')?[['token-reference','토큰 레퍼런스']]:[['token-introduction','디자인 토큰이란'],['token-structure','토큰의 구성'],['token-usage','토큰 사용하기']]):entry?[['preview','미리보기'],['usage','사용 지침'],['code','구현 코드'],['tokens','디자인 토큰'],['examples','기기 적용 예시']]:device?[['preview','화면 예시'],['usage','사용 범위']]:[['overview','개요']];
 const groupedComponents=classify(catalog,classification);
 const visibleGroups=showClassification||category==='all'?[{id:'all',title:'All components',description:'전체 컴포넌트를 중복 없이 살펴보세요.',items:catalog}]:groupedComponents.filter(group=>group.id===category);
 const selectCategory=id=>{setShowClassification(false);setCategory(id);setMenu(false);if(route!=='/components')window.location.assign('#/components');main.current?.scrollTo({top:0,behavior:'instant'});};
 const cards=(items)=><div className="catalog-grid">{items.map(item=><a className="catalog-card" href={'#'+item.path} key={item.path}><span className="card-category">{item.group||'GUIDE'}</span><h2>{item.title}<span aria-hidden="true">↗</span></h2><p>{item.description}</p></a>)}</div>;
 if(kind==='ai') return <AIChat handoff={assistantHandoff}/>;
 if(kind==='experience') return <Experience route={route}/>;
 if(kind==='start'&&valid) return <Landing/>;
 return <div className={`docs-workspace ${assistantOpen?'has-assistant':''}`}><div className={`docs-shell seed-layout ${kind==='components'&&!entry?'component-overview':''} ${assistantOpen?'assistant-expanded':''}`}><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();main.current?.focus();}}>본문으로 건너뛰기</a>
 <header className="topbar"><a href="#/start" className="wordmark"><span className="flow-mark shared-brand-symbol" aria-hidden="true"><i/><i/><i/></span><span className="shared-brand-name">flowthing</span></a><nav className="top-navigation" aria-label="Main navigation"><a href="#/foundations" aria-current={kind==='foundations'?'page':undefined}>Foundations</a><a href="#/components" onClick={()=>setShowClassification(true)} aria-current={kind==='components'?'page':undefined}>Components</a><a href="#/devices" aria-current={kind==='devices'?'page':undefined}>Device Library</a><a href="#/development" aria-current={kind==='development'?'page':undefined}>Development</a></nav><div className="header-actions"><div className="header-search-box"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="header-search-input" type="search" aria-label="Search components and devices" placeholder="Search components, devices…" value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd>{query.trim()&&<div className="header-search-results"><p role="status">{results.length} results</p>{results.map(item=><a key={item.path} href={'#'+item.path} onClick={()=>{setQuery('');setMenu(false);}}><strong>{item.title}</strong><small>{item.description}</small></a>)}</div>}</div><button className="doc-button mobile-menu" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>Menu</button></div></header>
 <aside className={`sidebar ${menu?'open':''}`} id="navigation"><nav aria-label="Documentation navigation">{kind==='development'?<div className="nav-section"><span className="nav-caption">Development</span>{link('/development','Overview')}{link('/ai','AI Chat ↗')}{validationPages.map(v=>link('/development/'+v[0],v[1]))}</div>:kind==='devices'?<><div className="nav-section"><span className="nav-caption">Device Library</span>{link('/devices','Overview')}{devices.map(d=>link('/devices/'+d[0],d[1]))}</div></>:<><div className="nav-section"><span className="nav-caption">Design System</span>{link('/foundations','Foundations')}{kind==='foundations'&&<div className="sidebar-children">{link('/foundations/design-token','Design Token')}{link('/foundations/design-token/reference','Reference')}</div>}{link('/components','Components')}{kind==='components'&&<div className="sidebar-children">{groupedComponents.map(group=><SidebarGroup key={`${classification}-${group.id}`} title={group.title} active={entry?group.items.some(c=>c.id===entry.id):!showClassification&&category===group.id} selected={!entry&&!showClassification&&category===group.id} selectionKey={`${category}-${entry?.id||'overview'}-${showClassification}`} onSelect={()=>selectCategory(group.id)}>{group.items.map(c=>link('/components/'+c.id,displayName(c.title)))}</SidebarGroup>)}</div>}</div></>}</nav><div className="sidebar-bottom">{link('/updates','Updates')}<span>Flowthing Design System</span></div></aside>

 <main id="main-content" ref={main} tabIndex={-1} className="docs-main"><div className="reading-layout"><article className="article" key={route}>
 <div className="breadcrumb">Flowthing <span>/</span> {entry?'Components':device?'Devices':kind==='development'?'Development':'Guide'} <span>/</span> {title}</div>
 {!valid?<><h1>페이지를 찾을 수 없어요</h1><p>주소를 확인하거나 컴포넌트 목록에서 다시 찾아보세요.</p><a href="#/components">컴포넌트 목록 →</a></>:entry?<>
 <div className="eyebrow">{entry.group.slice(0,-1).toUpperCase()} · {entry.behaviors.length?entry.behaviors.map(behaviorLabel).join(' / '):'SUPPORTING ELEMENT'}</div><h1>{displayName(entry.title)}</h1><p className="lead">{entry.description}</p><div className="page-meta"><span>기존 컴포넌트 · 실제 구현 기준</span><Copy text={location.href} label="페이지 링크 복사"/></div>
 <section id="preview"><h2>미리보기</h2><p>기존 컴포넌트를 직접 살펴보세요. 제어 예시는 실제 기기와 연결되지 않습니다.</p>{entry.id==='adaptive-light-slider'?<div className="component-preview-pair"><div><h3>Adaptive Light Slider</h3><Demo name="AdaptiveLightSlider"/></div><div><h3>Vertical Slider</h3><Demo name="VerticalSlider"/></div></div>:<Demo name={entry.title}/>}</section>
 <section id="usage"><h2>사용 지침</h2><p>{entry.description} 아래 구현 코드에서 지원하는 속성과 이벤트를 확인한 뒤 사용하세요.</p>{notes[entry.title]&&<div className="callout"><strong>현재 지원 범위</strong><p>{notes[entry.title]}</p></div>}<p className="muted">접근성 및 통신 상태 검증은 별도 개선 대상입니다. 미리보기의 동작만으로 제품 적용 검증이 완료된 것은 아닙니다.</p></section>
 <section id="code"><h2>구현 코드</h2><p>현재 소스에서 직접 읽은 코드입니다. 속성 이름과 기본값을 확인할 수 있습니다.</p><div className="code-toolbar"><code>{entry.source}</code><Copy text={source}/></div><details className="source-details"><summary>전체 구현 보기</summary><SourceCode source={source}/></details></section>
 <section id="tokens"><h2>디자인 토큰</h2><p>이 컴포넌트와 같은 폴더의 스타일에서 참조하는 토큰입니다. 하위 컴포넌트의 참조는 포함하지 않습니다.</p>{entry.tokens.length?<div className="token-list">{entry.tokens.map(token=><div key={token}><code>{token}</code><Copy text={token}/></div>)}</div>:<p>직접 참조하는 CSS 토큰이 없습니다. 하위 컴포넌트와 구현 코드를 확인하세요.</p>}</section>
 <section id="examples"><h2>기기 적용 예시</h2><p>이 컴포넌트가 직접 또는 하위 구성 요소로 사용된 화면입니다. 화면 전체를 펼쳐 표시합니다.</p>{examples.length ? examples.map(([id,name,description,page])=>{const Page=page;return <div className="device-example" key={id}><div className="example-heading"><div><h3>{name}</h3><p>{description}</p></div><a href={'#/devices/'+id}>기기 페이지 ↗</a></div><div className="device-preview"><Page onNavigate={target=>{location.hash='/devices/'+target;}}/></div></div>}):<div className="callout">현재 기기 화면에서 사용된 사례가 없습니다. 위 미리보기에서 개별 요소를 확인할 수 있습니다.</div>}</section>
 <div className="page-pagination">{catalog.indexOf(entry)>0&&link('/components/'+catalog[catalog.indexOf(entry)-1].id,'← '+catalog[catalog.indexOf(entry)-1].title)}{catalog.indexOf(entry)<catalog.length-1&&link('/components/'+catalog[catalog.indexOf(entry)+1].id,catalog[catalog.indexOf(entry)+1].title+' →')}</div>
 </>:device?<><div className="eyebrow">DEVICE EXAMPLE</div><h1>{device[1]}</h1><p className="lead">{device[2]}</p><section id="preview"><h2>화면 예시</h2><p><a href={device[0]==='dashboard'?'#/experience':'#/experience/'+device[0]}>모바일 전체 화면으로 체험하기 ↗</a></p><div className="device-preview">{(() => {const Page=device[3];return <Page onNavigate={id=>{location.hash='/devices/'+id;}}/>;})()}</div></section><section id="usage"><h2>사용 범위</h2><p>현재 로컬 상태로 동작하는 UI 예시입니다. 실제 기기 명령, 실패 복구, 재연결 정책은 공통 명세를 정리한 뒤 연결할 예정입니다.</p><a href="#/components">사용 가능한 컴포넌트 보기 →</a></section></>:<section id="overview">
 {kind==='components'?<><header className="components-heading"><h1>Components</h1><p className="lead">컴포넌트를 탐색할 분류 기준을 선택하세요.</p>{showClassification&&<div className="classification-cards" role="group" aria-label="컴포넌트 분류 기준"><button aria-pressed={classification==='behavior'} onClick={()=>{setClassification('behavior');selectCategory('binary');}}><span>By behavior</span><strong>제어 행동으로 보기</strong><p>Binary · Linear · State · Action</p><small>사용자가 기기를 어떻게 제어하는지 기준으로 탐색합니다.</small></button><button aria-pressed={classification==='assembly'} onClick={()=>{setClassification('assembly');selectCategory('atoms');}}><span>By assembly</span><strong>조립 단계로 보기</strong><p>Atom · Molecule · Organism</p><small>작은 요소부터 기기 구성까지 조립 단계로 탐색합니다.</small></button></div>}</header>{visibleGroups.map(group=><section className="component-category" key={group.id}><div className="component-category-heading"><h2>{group.title}</h2><p>{group.description}</p></div><ul className="component-gallery">{group.items.map(c=><li key={c.id}><a className="component-tile" href={'#/components/'+c.id}><ComponentThumbnail name={c.title}/><h3>{displayName(c.title)}</h3><span className="component-classification-label">{classification==='behavior'?c.group.slice(0,-1):c.behaviors.length?c.behaviors.map(behaviorLabel).join(' / '):'Supporting element'}</span></a></li>)}</ul></section>)}</>:kind==='foundations'?(tokenPage?<DesignToken reference={route.endsWith('/reference')}/>:<><div className="eyebrow">DESIGN FOUNDATIONS</div><h1>Foundations</h1><p className="lead">Flowthing을 구성하는 디자인의 기초를 살펴보세요.</p>{cards([{path:'/foundations/design-token',title:'Design Token',description:'디자인 토큰의 개념과 3단계 구성, 코드에서 사용하는 방법을 알아보세요.',group:'FOUNDATIONS'},{path:'/foundations/design-token/reference',title:'Reference',description:'색상, 타이포그래피, 그림자, 컴포넌트 토큰의 실제 정의를 확인하세요.',group:'DESIGN TOKEN'}])}</>):kind==='development'&&validationPage?.[0]!=='guide'?<Validation page={validationPage?.[0]}/>:kind==='devices'?<><h1>Devices</h1><p className="lead">컴포넌트가 실제 기기 화면에서 어떻게 조합되는지 살펴보세요.</p>{cards(devices.map(d=>({path:'/devices/'+d[0],title:d[1],description:d[2],group:'DEVICE'})))}</>:kind==='development'?<><h1>개발 가이드</h1><p className="lead">React 컴포넌트와 CSS 토큰으로 화면을 구성합니다.</p><h2>로컬 실행</h2><pre><code>{'npm ci\nnpm run dev'}</code></pre><h2>컴포넌트 사용</h2><p>각 문서의 구현 코드에서 실제 속성·기본값을 확인하세요. 기존 AI 가이드와 API가 다른 항목은 컴포넌트의 지원 범위에 표시했습니다.</p><h2>문서 주소</h2><p>GitHub Pages에서 직접 열기와 새로고침이 가능하도록 #/components/button 형태의 주소를 사용합니다.</p><a href="#/components">컴포넌트 찾아보기 →</a></>:<><h1>업데이트</h1><p className="lead">문서와 구성 요소의 변경을 기록합니다.</p><h2>2026.09.22 · 문서 구조 개편</h2><ul><li>25개 컴포넌트의 개별 문서와 미리보기 제공</li><li>검색, 페이지별 URL, 이전·다음 문서 탐색 추가</li><li>기기 데모를 Devices로 분리</li><li>현재 구현의 제약과 검토할 규칙 표시</li></ul></>}
 </section>}
 <footer className="doc-footer">Flowthing · Smart home, thoughtfully connected.</footer></article><aside className="toc" aria-label="이 페이지 목차"><span>이 페이지에서</span>{sections.map(([id,label])=><button key={id} onClick={()=>scrollTo(id)}>{label}</button>)}<a href="#/components">전체 컴포넌트 ↗</a></aside></div></main><AIQuickChat open={assistantOpen} onExpand={expandAssistant} context={{title,href:'#'+route,entry,deviceId:device?.[0]}} onClose={closeAssistant}/><button id="ai-floating-entry" className={`ai-floating-entry ${assistantOpen?'is-open':''}`} onClick={()=>assistantOpen?closeAssistant():setAssistantOpen(true)} aria-label={assistantOpen?'Flowthing AI 채팅 닫기':'현재 문서에 대해 Flowthing AI에게 질문하기'} aria-expanded={assistantOpen} aria-controls="ai-quick-panel"><span aria-hidden="true"><ThinkingOrb state="composing" size={32} theme="dark"/></span><span className="ai-floating-label" aria-hidden="true">Flowthing AI ↗</span></button></div></div>;
}
